"""screener fundamentals fields and ai_report

Revision ID: 81df8bc3bd04
Revises: ff3adbe72cdb
Create Date: 2026-07-05 09:21:10.655501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81df8bc3bd04'
down_revision: Union[str, Sequence[str], None] = 'ff3adbe72cdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=12), nullable=False),
    sa.Column('accession_no', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('report_md', sa.Text(), nullable=False),
    sa.Column('sections_meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_report_ticker'), 'ai_report', ['ticker'], unique=False)
    op.add_column('fact_fundamentals', sa.Column('current_ratio', sa.Float(), nullable=True))
    op.add_column('fact_fundamentals', sa.Column('total_cash', sa.Float(), nullable=True))
    op.add_column('fact_fundamentals', sa.Column('quarterly_operating_cashflow', sa.Float(), nullable=True))
    op.add_column('fact_fundamentals', sa.Column('insider_ownership_pct', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fact_fundamentals', 'insider_ownership_pct')
    op.drop_column('fact_fundamentals', 'quarterly_operating_cashflow')
    op.drop_column('fact_fundamentals', 'total_cash')
    op.drop_column('fact_fundamentals', 'current_ratio')
    op.drop_index(op.f('ix_ai_report_ticker'), table_name='ai_report')
    op.drop_table('ai_report')
    # ### end Alembic commands ###
