"""10b5-1 flag and next earnings date

Revision ID: 8aa46e54352f
Revises: 0e0c490addec
Create Date: 2026-07-06 19:59:18.050002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aa46e54352f'
down_revision: Union[str, Sequence[str], None] = '0e0c490addec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_fundamentals', sa.Column('next_earnings_date', sa.Date(), nullable=True))
    op.add_column('fact_insider_trade', sa.Column('is_10b5_1', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fact_insider_trade', 'is_10b5_1')
    op.drop_column('fact_fundamentals', 'next_earnings_date')
    # ### end Alembic commands ###
