"""initial schema

Revision ID: ff3adbe72cdb
Revises: 
Create Date: 2026-07-04 22:32:35.535829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff3adbe72cdb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_ticker',
    sa.Column('ticker', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('cik', sa.String(length=10), nullable=True),
    sa.Column('exchange', sa.String(length=32), nullable=True),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_index(op.f('ix_dim_ticker_cik'), 'dim_ticker', ['cik'], unique=False)
    op.create_table('fact_congress_trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chamber', sa.String(length=8), nullable=False),
    sa.Column('member', sa.String(length=128), nullable=False),
    sa.Column('ticker', sa.String(length=12), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('disclosure_date', sa.Date(), nullable=True),
    sa.Column('tx_type', sa.String(length=16), nullable=False),
    sa.Column('amount_low', sa.Float(), nullable=True),
    sa.Column('amount_high', sa.Float(), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chamber', 'member', 'ticker', 'transaction_date', 'tx_type', 'amount_low', name='uq_congress_trade_natural')
    )
    op.create_index(op.f('ix_fact_congress_trade_ticker'), 'fact_congress_trade', ['ticker'], unique=False)
    op.create_table('fact_fundamentals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=12), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('revenue_growth_yoy', sa.Float(), nullable=True),
    sa.Column('gross_margin', sa.Float(), nullable=True),
    sa.Column('operating_margin', sa.Float(), nullable=True),
    sa.Column('debt_to_equity', sa.Float(), nullable=True),
    sa.Column('pe', sa.Float(), nullable=True),
    sa.Column('forward_pe', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'as_of', name='uq_fundamentals_ticker_asof')
    )
    op.create_index(op.f('ix_fact_fundamentals_ticker'), 'fact_fundamentals', ['ticker'], unique=False)
    op.create_table('fact_insider_trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accession_no', sa.String(length=32), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=True),
    sa.Column('ticker', sa.String(length=12), nullable=False),
    sa.Column('insider_name', sa.String(length=128), nullable=True),
    sa.Column('insider_title', sa.String(length=128), nullable=True),
    sa.Column('is_officer', sa.Boolean(), nullable=True),
    sa.Column('is_director', sa.Boolean(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('shares', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_no', 'row_index', name='uq_insider_trade_accession_row')
    )
    op.create_index(op.f('ix_fact_insider_trade_cik'), 'fact_insider_trade', ['cik'], unique=False)
    op.create_index(op.f('ix_fact_insider_trade_ticker'), 'fact_insider_trade', ['ticker'], unique=False)
    op.create_table('fact_price',
    sa.Column('ticker', sa.String(length=12), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'date')
    )
    op.create_table('ingestion_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rows_upserted', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_run_source'), 'ingestion_run', ['source'], unique=False)
    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=12), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('components', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_ticker'), 'score', ['ticker'], unique=False)
    op.create_table('watchlist_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=12), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['dim_ticker.ticker'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_item')
    op.drop_index(op.f('ix_score_ticker'), table_name='score')
    op.drop_table('score')
    op.drop_index(op.f('ix_ingestion_run_source'), table_name='ingestion_run')
    op.drop_table('ingestion_run')
    op.drop_table('fact_price')
    op.drop_index(op.f('ix_fact_insider_trade_ticker'), table_name='fact_insider_trade')
    op.drop_index(op.f('ix_fact_insider_trade_cik'), table_name='fact_insider_trade')
    op.drop_table('fact_insider_trade')
    op.drop_index(op.f('ix_fact_fundamentals_ticker'), table_name='fact_fundamentals')
    op.drop_table('fact_fundamentals')
    op.drop_index(op.f('ix_fact_congress_trade_ticker'), table_name='fact_congress_trade')
    op.drop_table('fact_congress_trade')
    op.drop_index(op.f('ix_dim_ticker_cik'), table_name='dim_ticker')
    op.drop_table('dim_ticker')
    # ### end Alembic commands ###
